@host = http://localhost:5169

### Login
POST {{host}}/Login
Content-Type: application/json

### Get Projects
GET {{host}}/api/Projects
Accept: application/json

### Get Tasks for a Project
GET {{host}}/api/Projects/{projectId}/Tasks
Accept: application/json